name: thamle
description: Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  google_maps_flutter: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/Picture/
  uses-material-design: true

flutter_icons:
  image_path: "lib/Picture/logo.png"
  android: true